FROM registry.stage.redhat.io/rhel9/rhel-bootc:9.6

COPY ./embed_image.sh /usr/bin/
COPY ./copy_embedded_images.sh /usr/bin/

RUN <<PULL
/usr/bin/embed_image.sh registry.fedoraproject.org/fedora:latest
/usr/bin/embed_image.sh docker.io/library/busybox:latest
/usr/bin/embed_image.sh docker.io/library/alpine@sha256:ca1c944a4f8486a153024d9965aafbe24f5723c1d5c02f4964c045a16d19dc54 --all
PULL

COPY ./Containerfile.workaround /etc/containers/Containerfile
COPY ./reproducer.sh /usr/bin/reproducer.sh
